### ISSUE TITLE
editor spanish translation

### ISSUE THREAD

**Issue by geikha** [hydra-synth/l10n#2]
My draft:
https://hackmd.io/f0-mxREBQgG4i9EDmZQjxQ?edit

@flordefuego tell me what u think
if it looks OK to you i'll do a pull req.

**Comment by ojack** [comment]
@ritchse this looks great!

small note --- it needs to be in JSON rather than js to work with the editor. I went ahead and converted it here:
https://hackmd.io/hszf1RXOSaaO6VuA0U-oFA

And you can see live in the editor at: https://hydra.ojack.xyz/?l10n-lang=es&l10n-url=https%3A%2F%2Fhackmd.io%2Fhszf1RXOSaaO6VuA0U-oFA%2Fdownload

**Comment by ojack** [comment]
I also added it here: https://github.com/hydra-synth/l10n/blob/main/es/editor.json

will go ahead and add to the editor as well, we can edit if there are any changes :)

**Comment by geikha** [comment]
@ojack yh yh i was just using the ``` at the beginning because the highlighting bothered me while editing. i was going to remove it after any of you gave it a look but i'm glad you got to do it :)

also checked the live version and it looks great!
